name: flutter_e_commerce
description: "Professional E-Commerce App with Clean Architecture and Authentication"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

  # UI Components
  cupertino_icons: ^1.0.8
  
  # Networking (for future backend integration)
  http: ^1.2.2
  dio: ^5.7.0  # Alternative to http for advanced features
  
  # JSON Serialization
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  
  # Local Storage
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication & Security
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.2
  
  # Image Handling
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  
  # Utils & Helpers
  intl: ^0.20.2  # Date formatting and internationalization
  uuid: ^4.5.1   # Generate unique IDs
  
  # Navigation
  go_router: ^16.1.0  # Modern navigation (optional alternative to Navigator)
  
  # Loading & Animation
  shimmer: ^3.0.0  # Loading skeleton animation
  lottie: ^3.1.3   # Beautiful animations
  
  # Form Validation
  form_validator: ^2.1.1
  
  # Platform Integration
  url_launcher: ^6.3.1  # Open URLs, make calls
  
  # Development Tools
  logger: ^2.5.0  # Better logging
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  #json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true

  # Assets
  #assets:
   # - assets/images/
    #- assets/icons/
    #- assets/animations/
    
  # Custom fonts (optional)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700