name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Setup Flutter stable
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"  # Stable version with Dart 3.4.x
          channel: stable

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Build Flutter web release
      - name: Build Flutter web
        run: flutter build web --release

      # 5. Update base href for GitHub Pages
      - name: Update base href for GitHub Pages
        run: sed -i 's|<base href="/">|<base href="/E-commerce-Flutter-App/">|' build/web/index.html

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
